alias server='make CFLAGS=-DDEBUG server && ./server'
alias valserver='make CFLAGS=-g server && valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./server'
alias client='make CFLAGS=-DDEBUG client && ./client -f /tmp/LSOfilestorage.sk -W /mnt/e/Progetti/SOL-Project/config.txt'
alias valclient='make CFLAGS=-g client && valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./client -f /tmp/LSOfilestorage.sk -W /mnt/e/Progetti/SOL-Project/config.txt'
alias killserver='kill -SIGKILL $(ps -a | grep server | grep -oE "[0-9]{4,5}")'
alias clocall='cloc src'
